#!/usr/bin/env bash
# =============================================================================
# Hide other users' processes: /proc mounted with hidepid=invisible.
#
# Without it, any account can read every program's command line with ps,
# including a password a program was started with. With it, an account sees
# its own processes only; root still sees all.
#
#   group proc       exempt from the hiding, given to the services that need
#                    to see other processes: systemd-logind and polkit
#   /etc/fstab       one /proc line, reconciled rather than appended
#
# Does nothing against root, or against an account in the sudo group.
#
# Usage:
#   sudo add_hidepid.sh
#
# Safe to re-run: an unchanged fstab line and drop-ins are left alone.
#
# Exit codes:
#   0  /proc is mounted with hidepid=invisible
#   1  something needed for the run is missing or failed
# =============================================================================

export DEBIAN_FRONTEND=noninteractive

print_header()  { printf "\n\033[36m=== %s ===\033[0m\n" "$1"; }
print_info()    { printf "\033[36mℹ️ %s\033[0m\n" "$1"; }
print_status()  { printf "\033[34m🔧 %s\033[0m\n" "$1"; }
print_success() { printf "\033[32m✅ %s\033[0m\n" "$1"; }
print_action()  { printf "\033[33m👉 %s\033[0m\n" "$1"; }
print_error()   { printf "\033[31m❌ %s\033[0m\n" "$1"; }

GROUP="proc"
FSTAB="/etc/fstab"
# The services that read other processes: logind for sessions, polkit for
# deciding who may do what. Hidden from them, both misjudge.
EXEMPT_UNITS=("systemd-logind.service" "polkit.service")

print_header "Hide other users' processes"

if [ "$EUID" -ne 0 ]; then
    print_error "This script needs root."
    print_action "Run it with: sudo bash $0"
    exit 1
fi

# --- Pre-flight --------------------------------------------------------------
ERRORS=()
findmnt -n /proc >/dev/null 2>&1 || ERRORS+=("/proc is not mounted, so there is nothing to change.")
command -v systemctl >/dev/null 2>&1 || ERRORS+=("No systemctl: this script expects systemd.")
[ -w "$FSTAB" ] || ERRORS+=("Cannot write $FSTAB.")
if [ ${#ERRORS[@]} -gt 0 ]; then
    for e in "${ERRORS[@]}"; do print_error "$e"; done
    exit 1
fi
print_success "Pre-flight passed."

# --- The exempt group --------------------------------------------------------
if getent group "$GROUP" >/dev/null; then
    print_success "Group '$GROUP' exists."
else
    groupadd --system "$GROUP"
    print_success "Created group '$GROUP'."
fi

CHANGED_UNITS=()
for unit in "${EXEMPT_UNITS[@]}"; do
    if ! systemctl cat "$unit" >/dev/null 2>&1; then
        print_info "$unit is not installed, so it needs no exemption."
        continue
    fi
    dir="/etc/systemd/system/${unit}.d"
    file="$dir/hidepid.conf"
    want="# Generated by add_hidepid.sh. The next run overwrites it.
[Service]
SupplementaryGroups=$GROUP"
    if [ -f "$file" ] && [ "$(cat "$file")" = "$want" ]; then
        print_success "$unit already sees every process."
        continue
    fi
    mkdir -p "$dir"
    printf '%s\n' "$want" > "$file"
    CHANGED_UNITS+=("$unit")
    print_success "$unit gets group '$GROUP'."
done
if [ ${#CHANGED_UNITS[@]} -gt 0 ]; then
    systemctl daemon-reload
    for unit in "${CHANGED_UNITS[@]}"; do
        if ! systemctl try-restart "$unit"; then
            print_error "$unit did not restart: sudo journalctl -u $unit -n 20"
            exit 1
        fi
    done
fi

# --- fstab -------------------------------------------------------------------
LINE="proc /proc proc defaults,nosuid,nodev,noexec,relatime,hidepid=invisible,gid=$GROUP 0 0"
if grep -qxF "$LINE" "$FSTAB"; then
    print_success "$FSTAB already mounts /proc hidden."
else
    cp -p "$FSTAB" "$FSTAB.before-hidepid"
    # Any other /proc line is replaced, so a re-run never leaves two.
    awk '$2 != "/proc"' "$FSTAB.before-hidepid" > "$FSTAB"
    printf '%s\n' "$LINE" >> "$FSTAB"
    print_success "$FSTAB mounts /proc hidden (previous copy: $FSTAB.before-hidepid)."
fi

# --- Now, without a reboot ---------------------------------------------------
if ! OUT="$(mount -o remount,hidepid=invisible,gid="$GROUP" /proc 2>&1)"; then
    print_error "Remounting /proc failed:"
    printf '%s\n' "$OUT" | sed 's/^/   /'
    exit 1
fi

# --- Prove it ----------------------------------------------------------------
SEEN="$(setpriv --reuid=nobody --regid=nogroup --clear-groups ps -e --no-headers 2>/dev/null | wc -l)"
ALL="$(ps -e --no-headers | wc -l)"
if [ "$SEEN" -ge "$ALL" ]; then
    print_error "An ordinary account still sees all $ALL processes."
    exit 1
fi
print_success "An ordinary account sees $SEEN of $ALL processes; root sees all."
print_info "Exempt: root, group '$GROUP' (${EXEMPT_UNITS[*]})."
