#!/bin/bash

# -d / --debug: trace every command. Stripped from "$@" so it never reaches the
# script's own argument parsing.
DEBUG_MODE=0
_dbg_args=()
for _a in "$@"; do
    case "$_a" in
        -d|--debug) DEBUG_MODE=1 ;;
        *)          _dbg_args+=("$_a") ;;
    esac
done
set -- ${_dbg_args+"${_dbg_args[@]}"}
unset _a _dbg_args
[ "$DEBUG_MODE" = "1" ] && set -x

# =============================================================================
# fail2ban: stop password guessing on the services this machine exposes.
#
# Without it, SSH and the mail login ports accept unlimited wrong passwords, so
# a guesser can try forever. This bans an address after a handful of failures.
#
# The local subnet and the private ranges are never banned (ignoreip), so admin
# from the LAN or over a VPN can never lock itself out. Re-running is safe: the
# config is rewritten only when it changes, and fail2ban is reloaded not
# reinstalled.
# =============================================================================

export DEBIAN_FRONTEND=noninteractive

print_status() {
    printf "\e[34m🔧 %s\e[0m\n" "$1"
}

print_success() {
    printf "\e[32m✅ %s\e[0m\n" "$1"
}

print_warning() {
    printf "\e[33m⚠️ %s\e[0m\n" "$1"
}

print_error() {
    printf "\e[31m❌ %s\e[0m\n" "$1"
}

if [ "$EUID" -ne 0 ]; then
    echo -e "\e[31mThis script requires sudo privileges to run properly.\e[0m"
    echo -e "\e[33mPlease run with: sudo $0\e[0m"
    exit 1
fi

if ! command -v fail2ban-client >/dev/null 2>&1; then
    print_status "Installing fail2ban..."
    if ! apt-get update -qq >/dev/null 2>&1; then
        print_warning "apt-get update failed, trying the install anyway."
    fi
    if ! apt-get install -y -qq fail2ban >/dev/null 2>&1; then
        print_error "Could not install fail2ban."
        exit 1
    fi
    print_success "fail2ban installed."
else
    print_success "fail2ban already installed."
fi

# The local subnet, so a host on the LAN is never banned. The three private
# ranges below already cover the common home subnet and every VPN range, but the
# detected one is added explicitly in case the LAN uses a wider mask.
LAN_CIDR="$(ip -4 route show default 2>/dev/null | awk '{print $3}' | head -1 | sed -E 's/\.[0-9]+$/.0\/24/')"

JAIL="/etc/fail2ban/jail.local"
TMP_JAIL="$(mktemp)"
trap 'rm -f "$TMP_JAIL"' EXIT

{
    echo "# Generated by add_fail2ban.sh. Do not edit by hand: the next run"
    echo "# overwrites it."
    echo "#"
    echo "# ignoreip keeps the LAN and all private/VPN ranges un-bannable, so"
    echo "# admin from the local network or a tunnel can never lock itself out."
    echo "[DEFAULT]"
    echo "backend  = systemd"
    echo "ignoreip = 127.0.0.1/8 ::1 10.0.0.0/8 172.16.0.0/12 192.168.0.0/16${LAN_CIDR:+ $LAN_CIDR}"
    echo "bantime  = 1h"
    echo "findtime = 10m"
    echo "maxretry = 5"
    echo ""
    echo "[sshd]"
    echo "enabled = true"
    echo ""
    echo "# The mail login ports. Only enabled if the service is present, so this"
    echo "# script is safe on a machine without a mail stack: fail2ban simply"
    echo "# skips a jail whose log source does not exist."
    echo "[dovecot]"
    echo "enabled = true"
    echo ""
    echo "[postfix-sasl]"
    echo "enabled = true"
} > "$TMP_JAIL"

if [ -f "$JAIL" ] && cmp -s "$TMP_JAIL" "$JAIL"; then
    print_success "jail.local already correct."
else
    install -m 0644 -o root -g root "$TMP_JAIL" "$JAIL"
    print_success "Wrote $JAIL"
fi

systemctl enable fail2ban >/dev/null 2>&1
if systemctl restart fail2ban >/dev/null 2>&1; then
    print_success "fail2ban running with SSH and mail jails."
else
    print_error "fail2ban failed to start. Check: journalctl -u fail2ban -n 30"
    exit 1
fi
