#!/usr/bin/env bash
set -e

# -d / --debug: trace every command. Stripped from "$@" so it never reaches the
# script's own argument parsing.
DEBUG_MODE=0
_dbg_args=()
for _a in "$@"; do
    case "$_a" in
        -d|--debug) DEBUG_MODE=1 ;;
        *)          _dbg_args+=("$_a") ;;
    esac
done
set -- ${_dbg_args+"${_dbg_args[@]}"}
unset _a _dbg_args
[ "$DEBUG_MODE" = "1" ] && set -x

# =============================================================================
# A Jenkins folder per site, named after the site.
#
# add_jenkins.sh creates one job per hostings/jenkins/Jenkinsfile.*, which gives a job
# list of generic verbs where every job asks which row it is for. This creates
# the other half: a folder per row in hostings.conf, holding that row's jobs, so
# the folder IS the site and nothing has to be typed in.
#
#   ispaddress_api/
#       1-write-service-unit
#       2-write-apache-vhost
#       3-request-certificate
#       set-up-this-site
#       deploy-csharp-application
#
# THE JENKINSFILES ARE NOT COPIED. Every job here points at the same file in
# jenkins/, and the pipeline reads the row from its own folder name. So this
# stays one file per action in git rather than one per action per site.
#
# WHICH JOBS A ROW GETS depends on its type. A website has no unit to write; a
# mailbox has neither a unit nor a vhost, so it gets no folder at all.
#
# NEVER OVERWRITES, WITH ONE EXCEPTION. A job somebody has configured by hand is
# theirs, and re-running after adding a row creates only what is missing.
#
# The exception is the URL the job fetches its own Jenkinsfile from, which is
# repointed when it is wrong, with a backup. Everything else in a job is worth
# preserving; that one field is not, because a wrong value stops the job before
# it runs a line, so there is nothing to protect. Added 2026-09-05, after every
# job created since the SSH key was deleted failed at the clone and a rerun of
# this script could not repair a single one.
# =============================================================================

export DEBIAN_FRONTEND=noninteractive

# --- Inline utility functions (always defined, no sourcing required) ---
print_status()  { printf "\033[34m🔧 %s\033[0m\n" "$1"; }
print_success() { printf "\033[32m✅ %s\033[0m\n" "$1"; }
print_warning() { printf "\033[33m⚠️ %s\033[0m\n" "$1"; }
# Yellow means "this needs you", never "warning": a question, an instruction,
# a URL to go and open. Anything the reader cannot act on is cyan.
# Conventions: bash-installer-conventions.md.
print_action()  { printf "\033[33m👉 %s\033[0m\n" "$1"; }
print_info()    { printf "\033[36mℹ️ %s\033[0m\n" "$1"; }

print_error()   { printf "\033[31m❌ %s\033[0m\n" "$1"; }
print_header()  { printf "\n\033[1m=== %s ===\033[0m\n" "$1"; }

usage() {
    echo "Usage: $0 [--dry-run] [--prune]" >&2
    echo "" >&2
    echo "  --dry-run   list what would be created, write nothing" >&2
    echo "  --prune     also delete folders whose row is gone from the config" >&2
    echo "" >&2
    echo "Environment:" >&2
    echo "  SITES_CONF    override the config location" >&2
    echo "  JENKINS_HOME  override where Jenkins keeps its jobs" >&2
    exit 1
}

DRY_RUN=0
PRUNE=0
while [ $# -gt 0 ]; do
    case "$1" in
        --dry-run) DRY_RUN=1; shift ;;
        --prune)   PRUNE=1; shift ;;
        -h|--help) usage ;;
        *) print_error "Unknown option: $1"; usage ;;
    esac
done

# Only a folder carrying this line is ever deleted. Jenkins' own jobs, and any
# folder somebody made by hand, do not have it and are left alone.
GENERATED_MARK="<!-- generated by add_jenkins_site_jobs.sh, safe to prune -->"

if [ "$DRY_RUN" -ne 1 ] && [ "$EUID" -ne 0 ]; then
    print_error "This script writes into Jenkins' home, so it needs sudo."
    print_action "Run with: sudo $0"
    print_action "Or see what it would do first: $0 --dry-run"
    exit 1
fi

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
. "$SCRIPT_DIR/config.sh" 2>/dev/null \
    || . /usr/local/lib/linuxbasics/hostings/scripts/config.sh 2>/dev/null \
    || conf_active() { printf '%s/hostings.conf' "$1"; }
SITES_CONF="${SITES_CONF:-$(conf_active "/etc/hostings")}"
JENKINS_HOME="${JENKINS_HOME:-/var/lib/jenkins}"

[ -f "$SITES_CONF" ] || { print_error "Config not found: $SITES_CONF"; exit 1; }

if [ "$DRY_RUN" -ne 1 ] && [ ! -d "$JENKINS_HOME/jobs" ]; then
    print_error "No Jenkins jobs directory at $JENKINS_HOME/jobs."
    print_action "Run add_jenkins.sh first."
    exit 1
fi

# The repository these jobs check out. Read from the working copy rather than
# written down, so a fork or a rename needs no edit here.
GIT_URL="$(git -C "$REPO_ROOT" remote get-url origin 2>/dev/null || true)"
GIT_BRANCH="$(git -C "$REPO_ROOT" rev-parse --abbrev-ref HEAD 2>/dev/null || true)"
# Detached at a pinned commit (a submodule): follow the branch that holds it, as
# add_jenkins.sh does. "*/HEAD" fetches refs/heads/HEAD, which never exists.
if [ "$GIT_BRANCH" = "HEAD" ]; then
    GIT_BRANCH="$(git -C "$REPO_ROOT" for-each-ref --contains HEAD --format='%(refname:lstrip=3)' refs/remotes/origin 2>/dev/null \
                  | grep -vx HEAD | head -1 || true)"
fi

# HTTPS, and the direction of this conversion is the whole point.
#
# It rewrote https:// INTO git@ until 2026-09-05, which was right while Jenkins
# had its own SSH key. That key was deleted on 2026-09-04 and every job moved to
# HTTPS with the GitHub App, but this generator was missed: jobs created after
# that migrated fine and jobs created AFTERWARDS were born broken, failing at
#
#   GitSCMFileSystem ... git@github.com: Permission denied (publickey)
#
# before the pipeline had run a single line. A newly created site therefore
# could not deploy at all, which is how it was found.
#
# Item 75 is the same bug one level down: /var/lib/jenkins/.gitconfig carried an
# insteadOf that rewrote https back to git@ inside git, so the job config said
# HTTPS and git still dialled SSH.
case "$GIT_URL" in
    git@*)
        GIT_URL="https://$(echo "$GIT_URL" | sed -E 's#^git@([^:]+):#\1/#')" ;;
esac

if [ -z "$GIT_URL" ] || [ -z "$GIT_BRANCH" ]; then
    print_error "Could not read the git remote or branch, so no jobs were created."
    exit 1
fi

print_header "Jenkins site folders"
print_status "Config:  $SITES_CONF"
print_status "Jenkins: $JENKINS_HOME"
print_status "Repo:    $GIT_URL ($GIT_BRANCH)"
[ "$DRY_RUN" -eq 1 ] && print_info "Dry run: nothing will be written."

trim() { echo "$1" | sed -E 's/^[[:space:]]+//; s/[[:space:]]+$//'; }

# Does this row exist in this environment? An empty Envs field means all of
# them, which is the common case: a row names environments only to narrow them.
row_in_env() {
    local list e
    list="$(trim "$1")"
    # An if, not `[ ] || [ ] && return`. That compound returns non-zero when
    # neither test matches, and under `set -e` the whole script exits there.
    if [ -z "$list" ] || [ "$list" = "-" ]; then
        return 0
    fi
    IFS=',' read -r -a _rie <<< "$list"
    for e in ${_rie+"${_rie[@]}"}; do
        [ "$(trim "$e")" = "$2" ] && return 0
    done
    return 1
}

# The environments to make a deploy job for. From the config, so adding one to
# ENVS gives every website a job for it on the next run rather than needing this
# script edited.
ALL_ENVS_RAW="$(sed -n 's/^[[:space:]]*ENVS[[:space:]]*=//p' "$SITES_CONF" | head -1)"
ALL_ENVS_RAW="${ALL_ENVS_RAW%%#*}"
IFS=',' read -r -a DEPLOY_ENVS <<< "$ALL_ENVS_RAW"
for i in "${!DEPLOY_ENVS[@]}"; do DEPLOY_ENVS[$i]="$(trim "${DEPLOY_ENVS[$i]}")"; done

xml_escape() { echo "$1" | sed 's/&/\&amp;/g; s/</\&lt;/g; s/>/\&gt;/g'; }

EXPECTED=()

write_folder() {
    local name="$1" desc="$2" dir="$JENKINS_HOME/jobs/$1"
    EXPECTED+=("$name")
    if [ -d "$dir" ] && [ -f "$dir/config.xml" ]; then
        # One repair, not a change: a folder written before 2026-08-15 carries a
        # hand-written <folderViews> block whose back-reference Jenkins cannot
        # resolve, which shows as "An error occurred when retrieving jobs for
        # this view" on an empty page. Anything else is left as it was made.
        if grep -q "<folderViews" "$dir/config.xml" 2>/dev/null; then
            print_info "Folder '$name' had a hand-written view, rewriting it."
        elif ! grep -qF "$GENERATED_MARK" "$dir/config.xml" 2>/dev/null; then
            # Written before pruning existed. Adding the mark is what lets a
            # later --prune recognise it as ours rather than leaving it forever.
            print_info "Folder '$name' predates the prune mark, rewriting it."
        else
            print_success "Folder '$name' already exists, left alone."
            return 0
        fi
    fi
    if [ "$DRY_RUN" -eq 1 ]; then
        print_status "would create folder '$name'"
        return 0
    fi
    mkdir -p "$dir/jobs"
    # NO <folderViews> BLOCK ON PURPOSE. Writing one by hand means writing an
    # XStream back-reference from the view to its folder, and getting that path
    # wrong gives "An error occurred when retrieving jobs for this view" with
    # nothing on the page. Jenkins builds the default view itself when the
    # element is absent, which is the one spelling that cannot be wrong.
    cat > "$dir/config.xml" <<XML
<?xml version='1.1' encoding='UTF-8'?>
${GENERATED_MARK}
<com.cloudbees.hudson.plugins.folder.Folder plugin="cloudbees-folder">
  <actions/>
  <description>$(xml_escape "$desc")</description>
  <properties/>
  <healthMetrics/>
  <icon class="com.cloudbees.hudson.plugins.folder.icons.StockFolderIcon"/>
</com.cloudbees.hudson.plugins.folder.Folder>
XML
    print_success "Folder '$name' created."
}

# One job inside a folder, pointing at a Jenkinsfile that reads the row from the
# folder name. Same XML as add_jenkins.sh writes, so the two stay comparable.
write_job() {
    local folder="$1" job="$2" jenkinsfile="$3" desc="$4" triggers="${5:-}"
    local triggers_xml="<triggers/>"
    # A declarative pipeline syncs its own triggers into the job, but only
    # AFTER a first build. A job that has never run would be invisible to a
    # webhook, which is exactly when it is most likely to be pushed to.
    [ "$triggers" = "push" ] && triggers_xml="<triggers>
    <com.cloudbees.jenkins.GitHubPushTrigger plugin=\"github\">
      <spec></spec>
    </com.cloudbees.jenkins.GitHubPushTrigger>
  </triggers>"
    local dir="$JENKINS_HOME/jobs/$folder/jobs/$job"

    if [ ! -f "$REPO_ROOT/hostings/jenkins/$jenkinsfile" ]; then
        print_info "No $jenkinsfile in jenkins/, so '$folder/$job' was skipped."
        return 0
    fi
    if [ -f "$dir/config.xml" ]; then
        EXPECTED_JOBS+=("$folder/$job")

        # SELF-HEALING, for the ONE thing that stops a job before it runs: the
        # URL it fetches its own Jenkinsfile from.
        #
        # Everything else in an existing job is deliberately left alone, because
        # Jenkins rewrites a config it has loaded and a generator that reasserts
        # itself would fight the operator. The clone URL is different: get it
        # wrong and the job cannot start at all, so there is nothing to preserve.
        #
        # This exists because on 2026-09-05 every job created since the SSH key
        # was deleted failed at "Permission denied (publickey)" before running a
        # line, and "already exists, left alone" meant a rerun could never repair
        # one. Item 75 had to migrate twelve jobs through the API by hand for the
        # same reason.
        local cur
        cur="$(sed -n 's#.*<url>\(.*\)</url>.*#\1#p' "$dir/config.xml" | head -1)"
        if [ -n "$cur" ] && [ "$cur" != "$GIT_URL" ]; then
            if [ "$DRY_RUN" -eq 1 ]; then
                print_status "  would repoint $folder/$job: $cur -> $GIT_URL"
                return 0
            fi
            cp -a "$dir/config.xml" "$dir/config.xml.bak-$(date +%Y%m%d-%H%M%S)"
            sed -i "s#<url>${cur//#/\\#}</url>#<url>${GIT_URL//#/\\#}</url>#" "$dir/config.xml"
            # A private repository over HTTPS needs the credential the SSH URL
            # never did, so it is added in the same pass rather than one failure
            # later.
            grep -q '<credentialsId>' "$dir/config.xml" \
                || sed -i "s#<url>${GIT_URL//#/\\#}</url>#<url>${GIT_URL//#/\\#}</url>\n          <credentialsId>github-token</credentialsId>#" "$dir/config.xml"
            chown jenkins:jenkins "$dir/config.xml" 2>/dev/null || true
            REPOINTED=$((REPOINTED + 1))
            print_status "  $folder/$job repointed: $cur -> $GIT_URL"
        fi

        # The branch and the Jenkinsfile path stop a job before it runs just as
        # surely as the URL, so they are repaired by the same rule.
        local cur_branch want_path cur_path healed=0
        cur_branch="$(sed -n 's#.*<name>\*/\(.*\)</name>.*#\1#p' "$dir/config.xml" | head -1)"
        want_path="hostings/jenkins/$jenkinsfile"
        cur_path="$(sed -n 's#.*<scriptPath>\(.*\)</scriptPath>.*#\1#p' "$dir/config.xml" | head -1)"
        if [ "$DRY_RUN" -ne 1 ] && { [ "$cur_branch" != "$GIT_BRANCH" ] || [ "$cur_path" != "$want_path" ]; }; then
            cp -a "$dir/config.xml" "$dir/config.xml.bak-$(date +%Y%m%d-%H%M%S)"
        fi
        if [ -n "$cur_branch" ] && [ "$cur_branch" != "$GIT_BRANCH" ]; then
            if [ "$DRY_RUN" -eq 1 ]; then
                print_status "  would move $folder/$job: */$cur_branch -> */$GIT_BRANCH"
            else
                sed -i "s#<name>\*/${cur_branch}</name>#<name>*/${GIT_BRANCH}</name>#" "$dir/config.xml"
                print_status "  $folder/$job branch: */$cur_branch -> */$GIT_BRANCH"
                healed=1
            fi
        fi
        if [ -n "$cur_path" ] && [ "$cur_path" != "$want_path" ]; then
            if [ "$DRY_RUN" -eq 1 ]; then
                print_status "  would point $folder/$job at $want_path"
            else
                sed -i "s#<scriptPath>${cur_path}</scriptPath>#<scriptPath>${want_path}</scriptPath>#" "$dir/config.xml"
                print_status "  $folder/$job Jenkinsfile: $cur_path -> $want_path"
                healed=1
            fi
        fi
        if [ "$healed" -eq 1 ]; then
            chown jenkins:jenkins "$dir/config.xml" 2>/dev/null || true
            REPOINTED=$((REPOINTED + 1))
            return 0
        fi
        [ -n "$cur" ] && [ "$cur" != "$GIT_URL" ] && return 0

        print_success "  $folder/$job already exists, left alone."
        return 0
    fi
    if [ "$DRY_RUN" -eq 1 ]; then
        EXPECTED_JOBS+=("$folder/$job")
        print_status "  would create $folder/$job  →  $jenkinsfile"
        return 0
    fi

    EXPECTED_JOBS+=("$folder/$job")
    mkdir -p "$dir"
    cat > "$dir/config.xml" <<XML
<?xml version='1.1' encoding='UTF-8'?>
<flow-definition plugin="workflow-job">
  <description>$(xml_escape "$desc")</description>
  <keepDependencies>false</keepDependencies>
  <properties/>
  <definition class="org.jenkinsci.plugins.workflow.cps.CpsScmFlowDefinition" plugin="workflow-cps">
    <scm class="hudson.plugins.git.GitSCM" plugin="git">
      <configVersion>2</configVersion>
      <userRemoteConfigs>
        <hudson.plugins.git.UserRemoteConfig>
          <url>${GIT_URL}</url>
          <credentialsId>github-token</credentialsId>
        </hudson.plugins.git.UserRemoteConfig>
      </userRemoteConfigs>
      <branches>
        <hudson.plugins.git.BranchSpec>
          <name>*/${GIT_BRANCH}</name>
        </hudson.plugins.git.BranchSpec>
      </branches>
      <doGenerateSubmoduleConfigurations>false</doGenerateSubmoduleConfigurations>
      <submoduleCfg class="empty-list"/>
      <!-- IgnoreNotifyCommit: THIS repository must not trigger the job.
           This SCM exists only to fetch the Jenkinsfile. Without it, every
           push to the config repository started a deploy of every website: 19 unasked-for
           builds in one evening on 2026-08-23, each one republishing a live
           site because an install script had changed. The site's own
           repository is checked out inside the pipeline and still triggers. -->
      <extensions>
        <hudson.plugins.git.extensions.impl.IgnoreNotifyCommit/>
      </extensions>
    </scm>
    <scriptPath>hostings/jenkins/${jenkinsfile}</scriptPath>
    <lightweight>true</lightweight>
  </definition>
  ${triggers_xml}
  <disabled>false</disabled>
</flow-definition>
XML
    print_success "  $folder/$job created."
}

FOLDERS=0
REPOINTED=0
EXPECTED_JOBS=()
SKIPPED=()

while IFS='|' read -r type name _port _path sub _ds _opts _auth _repo _branch _envs _users _mode _rt _enabled _owner; do
    type="$(trim "${type%%#*}")"
    name="$(trim "$name")"
    sub="$(trim "$sub")"
    [ -z "$type" ] && continue
    [ -z "$name" ] && continue

    case "$type" in
        app)
            write_folder "$name" "The $name application: its unit, its address, its certificate and its deploys."
            write_job "$name" "1-write-service-unit"      "Jenkinsfile.site-1-write-service-unit"      "Write the systemd unit for $name."
            write_job "$name" "2-write-apache-vhost"      "Jenkinsfile.site-2-write-apache-vhost"      "Write the Apache vhost for $name."
            write_job "$name" "3-request-certificate"     "Jenkinsfile.site-3-request-certificate"     "Request the certificate for $name."
            write_job "$name" "set-up-this-site"          "Jenkinsfile.site-all-set-up-one-site"       "Run all of the above for $name, in order."
            write_job "$name" "deploy-csharp-application" "Jenkinsfile.app-2-deploy-csharp-application" "Put an already built version of $name on the machine."
            # The unattended path: source to running service, started by a push.
            # deploy-csharp-application above stays for the hand-driven case,
            # where a staging path is pasted in between building and deploying.
            for _env in ${DEPLOY_ENVS+"${DEPLOY_ENVS[@]}"}; do
                [ -z "$_env" ] && continue
                row_in_env "$_envs" "$_env" || continue
                write_job "$name" "deploy-${_env}" "Jenkinsfile.app-1-build-and-deploy" \
                    "Build $name from source and deploy it into its ${_env} environment." \
                    push
            done
            FOLDERS=$(( FOLDERS + 1 ))
            ;;
        website|php|docroot)
            write_folder "$name" "The $name website: files served off disk, so no unit and no build."
            write_job "$name" "2-write-apache-vhost"    "Jenkinsfile.site-2-write-apache-vhost"    "Write the Apache vhost for $name."
            write_job "$name" "3-request-certificate"   "Jenkinsfile.site-3-request-certificate"   "Request the certificate for $name."
            write_job "$name" "set-up-this-site"        "Jenkinsfile.site-all-set-up-one-site"     "Run all of the above for $name, in order."
            # ONE DEPLOY JOB PER ENVIRONMENT, and the name carries which.
            #
            # A single job taking the branch as a parameter cannot be triggered
            # by a push: the hook says which branch changed, the job would build
            # with its default, and a push to test would publish to live. Each
            # job here is pinned to one branch, which is what makes the trigger
            # safe to switch on.
            for _env in ${DEPLOY_ENVS+"${DEPLOY_ENVS[@]}"}; do
                [ -z "$_env" ] && continue
                # Only environments the row actually exists in. example-net
                # is live-only, and it was given deploy-test, deploy-accept and
                # deploy-skunk: three jobs with no branch to build and no
                # document root to publish into, failing every time anyone ran
                # them.
                row_in_env "$_envs" "$_env" || continue
                write_job "$name" "deploy-${_env}" "Jenkinsfile.web-1-deploy-static-website" \
                    "Publish the ${_env} branch of $name into its ${_env} document root." \
                    push
            done
            FOLDERS=$(( FOLDERS + 1 ))
            ;;
        proxy)
            write_folder "$name" "The $name proxy: something else runs it, this only publishes the address."
            write_job "$name" "2-write-apache-vhost"  "Jenkinsfile.site-2-write-apache-vhost"  "Write the Apache vhost for $name."
            write_job "$name" "3-request-certificate" "Jenkinsfile.site-3-request-certificate" "Request the certificate for $name."
            write_job "$name" "set-up-this-site"      "Jenkinsfile.site-all-set-up-one-site"   "Run both of the above for $name."
            FOLDERS=$(( FOLDERS + 1 ))
            ;;
        mailbox)
            # No unit, no vhost, nothing to build. A folder would hold nothing.
            SKIPPED+=("$name (mailbox: no unit and no vhost)")
            ;;
        *)
            SKIPPED+=("$name (unknown type '$type')")
            ;;
    esac
# A SETTING, not a row. PANEL lines hold pipes too, and read as rows they
# became three sites called 10002, 10001 and 10000, each warned about on every
# run. Same guard as conf_rows() in the generators.
done < <(grep -v '^[[:space:]]*#' "$SITES_CONF" \
    | grep -vE '^[[:space:]]*[A-Za-z_][A-Za-z0-9_]*[[:space:]]*=' \
    | grep '|')

echo ""
print_status "$FOLDERS site folder(s) handled."
if [ ${#SKIPPED[@]} -gt 0 ]; then
    print_info "No folder for:"
    for s in "${SKIPPED[@]}"; do print_info "  - $s"; done
fi

# -----------------------------------------------------------------------------
# Jobs this run did not ask for, inside folders it did.
#
# Folder-level pruning below does not see these: the row still exists, so the
# folder stays, and a job that has been renamed or replaced sits there looking
# runnable. That is not hypothetical. deploy-static-website became one job per
# environment on 2026-08-23, and without this the old one would have stayed
# next to the four that replaced it, deploying live whenever anybody clicked it.
#
# Only jobs carrying the generated mark are touched. Anything made by hand in
# the Jenkins UI is left alone and not even reported, because it was not ours
# to make and is not ours to remove.
# -----------------------------------------------------------------------------
STALE_JOBS=()
for dir in "$JENKINS_HOME"/jobs/*/jobs/*/; do
    [ -d "$dir" ] || continue
    job="$(basename "$dir")"
    folder="$(basename "$(dirname "$(dirname "$dir")")")"

    # Only inside a folder this run owns. add_jenkins.sh owns csharp/ and
    # machine/, and reporting its jobs here said "nothing generates this" about
    # jobs another script writes on every run.
    in_site_folder=0
    for e in ${EXPECTED+"${EXPECTED[@]}"}; do
        [ "$e" = "$folder" ] && in_site_folder=1 && break
    done
    [ "$in_site_folder" -eq 0 ] && continue

    # IDENTIFIED BY NAME, NOT BY A MARK IN THE FILE.
    #
    # Jenkins rewrites a job's config.xml when it loads it, normalising the XML
    # and stamping the plugin version in, and an XML comment does not survive
    # that. A mark-based check called every generated job foreign, so --prune
    # reported plenty and deleted nothing.
    #
    # These names are this script's vocabulary. A job in a folder it owns,
    # carrying one of them, is its to manage. Anything else in that folder was
    # made by hand and is neither touched nor mentioned.
    case "$job" in
        1-write-service-unit|2-write-apache-vhost|3-request-certificate|set-up-this-site|deploy-*) ;;
        *) continue ;;
    esac

    known=0
    for e in ${EXPECTED_JOBS+"${EXPECTED_JOBS[@]}"}; do
        [ "$e" = "$folder/$job" ] && known=1 && break
    done
    [ "$known" -eq 0 ] && STALE_JOBS+=("$folder/$job")
done

if [ ${#STALE_JOBS[@]} -gt 0 ]; then
    echo ""
    if [ "$PRUNE" -eq 1 ] && [ "$DRY_RUN" -ne 1 ]; then
        for s in "${STALE_JOBS[@]}"; do
            rm -rf "${JENKINS_HOME:?}/jobs/${s%%/*}/jobs/${s##*/}"
            print_success "Deleted job '$s', nothing generates it any more."
        done
    else
        print_info "These jobs are no longer generated by anything:"
        for s in "${STALE_JOBS[@]}"; do print_info "  - $s"; done
        print_action "Delete them, and their build history, with:"
        print_action "  sudo $0 --prune"
    fi
fi

# -----------------------------------------------------------------------------
# Folders whose row has gone.
#
# Reported by default and deleted only with --prune, the same split
# maintain_services.sh uses. A leftover folder still looks runnable, which is
# the confusion this removes.
#
# Build history goes with it, so this only ever touches folders carrying the
# generated mark.
# -----------------------------------------------------------------------------
ORPHANS=()
for dir in "$JENKINS_HOME"/jobs/*/; do
    [ -d "$dir" ] || continue
    folder="$(basename "$dir")"
    # A directory with no config.xml is not a job, it is debris: the skeleton a
    # running Jenkins writes back after an earlier prune deleted the files from
    # under it. Nothing reads it and nothing can run it, so it is an orphan
    # whatever its name, and the generated-mark test below would skip it
    # forever because the mark lived in the file that was deleted.
    if [ ! -f "$dir/config.xml" ]; then
        ORPHANS+=("$folder")
        continue
    fi
    grep -qF "$GENERATED_MARK" "$dir/config.xml" 2>/dev/null || continue
    known=0
    for e in ${EXPECTED+"${EXPECTED[@]}"}; do
        [ "$e" = "$folder" ] && known=1 && break
    done
    [ "$known" -eq 0 ] && ORPHANS+=("$folder")
done

if [ ${#ORPHANS[@]} -gt 0 ]; then
    echo ""
    if [ "$PRUNE" -eq 1 ] && [ "$DRY_RUN" -ne 1 ]; then
        # ASK JENKINS FIRST, then clean the disk.
        #
        # A running Jenkins holds every job in memory. `rm -rf` alone deletes
        # the files and Jenkins writes a skeleton straight back: no config.xml,
        # but jobs/<name>/builds and nextBuildNumber reappear, so the folder is
        # gone from the UI and still on disk forever. Measured 2026-09-03 on
        # sandbox_test, reloadtest and example_org, all three left behind by
        # a prune that reported success.
        #
        # doDelete makes Jenkins forget it first, which is also what keeps its
        # in-memory state consistent. The rm afterwards is the fallback for a
        # Jenkins that is stopped or does not answer.
        _url="${JENKINS_URL:-http://127.0.0.1:11002}"
        _tok="${TOKEN_FILE:-/var/lib/hosting-manager/jenkins-token}"
        for o in "${ORPHANS[@]}"; do
            if systemctl is-active --quiet jenkins 2>/dev/null && [ -s "$_tok" ]; then
                curl -fsS -o /dev/null --max-time 30 -X POST \
                    -u "$(head -n1 "$_tok")" "${_url}/job/${o}/doDelete" 2>/dev/null || true
            fi
            rm -rf "${JENKINS_HOME:?}/jobs/${o:?}"
            if [ -d "${JENKINS_HOME}/jobs/${o}" ]; then
                print_action "Deleted folder '$o', but Jenkins wrote it back. Rerun once it is idle."
            else
                print_success "Deleted folder '$o', its row is gone from the config."
            fi
        done
    else
        print_info "No row for these folders any more:"
        for o in "${ORPHANS[@]}"; do print_info "  - $o"; done
        print_action "Delete them, and their build history, with:"
        print_action "  sudo $0 --prune"
    fi
fi

if [ "$DRY_RUN" -eq 1 ]; then
    echo ""
    print_status "Dry run, nothing was written. Run it for real with:"
    print_status "  sudo $0"
    exit 0
fi

chown -R jenkins:jenkins "$JENKINS_HOME/jobs" 2>/dev/null || true

# Jenkins reads jobs at startup, so newly written ones need a reload.
#
# RELOADED, NOT RESTARTED. A restart kills whatever Jenkins is running, and this
# script is called from the apply pipeline: on 2026-09-03 00:21 it restarted
# Jenkins under a running build, which then reported SUCCESS in its log while
# the API still called it building. /reload rereads every config.xml with no
# downtime and no build lost.
if systemctl is-active --quiet jenkins 2>/dev/null; then
    _url="${JENKINS_URL:-http://127.0.0.1:11002}"
    _tok="${TOKEN_FILE:-/var/lib/hosting-manager/jenkins-token}"
    if [ -s "$_tok" ] && curl -fsS -o /dev/null --max-time 30 -X POST \
            -u "$(head -n1 "$_tok")" "${_url}/reload" 2>/dev/null; then
        # A reload is not instant. Jenkins answers 503 while it re-reads every
        # config.xml, so a caller that starts a build straight after gets a
        # queue item against jobs that are then replaced, and it never
        # schedules. Wait here so nobody downstream has to know that.
        for _i in $(seq 1 60); do
            curl -fsS -o /dev/null --max-time 5 \
                -u "$(head -n1 "$_tok")" "${_url}/api/json?tree=mode" 2>/dev/null && break
            sleep 2
        done
        print_success "Jenkins reloaded, so it sees the new folders."
    else
        print_action "Could not reload Jenkins, so it may not see the new folders yet."
        print_action "  Reload it from Manage Jenkins, or restart it when nothing is building."
    fi
else
    print_info "Jenkins is not running, so the folders appear when it next starts."
fi
