#!/usr/bin/env bash
set -e

# -d / --debug: trace every command. Stripped from "$@" so it never reaches the
# script's own argument parsing.
DEBUG_MODE=0
_dbg_args=()
for _a in "$@"; do
    case "$_a" in
        -d|--debug) DEBUG_MODE=1 ;;
        *)          _dbg_args+=("$_a") ;;
    esac
done
set -- ${_dbg_args+"${_dbg_args[@]}"}
unset _a _dbg_args
[ "$DEBUG_MODE" = "1" ] && set -x

# =============================================================================
# The weekly look for new stable releases of every upstream package
# (upstream/README.md). Writes upstream-check.service and its timer.
#
# It runs the root-owned copy under /usr/local/lib/linuxbasics, never the home
# clone: that copy is the one no other account can write to.
# =============================================================================

print_header()  { printf "\n\033[36m=== %s ===\033[0m\n" "$1"; }
print_info()    { printf "\033[36mℹ️ %s\033[0m\n" "$1"; }
print_status()  { printf "\033[34m🔧 %s\033[0m\n" "$1"; }
print_success() { printf "\033[32m✅ %s\033[0m\n" "$1"; }
print_action()  { printf "\033[33m👉 %s\033[0m\n" "$1"; }
print_error()   { printf "\033[31m❌ %s\033[0m\n" "$1"; }

[ "$EUID" -eq 0 ] || { print_error "This needs root: it writes systemd units."; print_action "sudo bash $0"; exit 2; }

PIPELINE_ROOT="/usr/local/lib/linuxbasics"
CHECK="$PIPELINE_ROOT/hostings/scripts/upstream_check.sh"
[ -f "$CHECK" ] || { print_error "No $CHECK yet."; print_action "sudo bash $(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/add_pipeline_scripts.sh"; exit 1; }

print_header "Weekly upstream release check"

cat > /etc/systemd/system/upstream-check.service <<EOF
# Generated by add_upstream_check_timer.sh. Edit the script, not this file.
[Unit]
Description=Build new stable releases of upstream packages and put them on test
After=network-online.target docker.service
Wants=network-online.target

[Service]
Type=oneshot
ExecStart=/bin/bash ${CHECK}
EOF

cat > /etc/systemd/system/upstream-check.timer <<'EOF'
# Generated by add_upstream_check_timer.sh. Edit the script, not this file.
[Unit]
Description=Weekly upstream release check

[Timer]
OnCalendar=Mon 04:00
Persistent=true

[Install]
WantedBy=timers.target
EOF

GATE="$PIPELINE_ROOT/hostings/scripts/upstream_gate.sh"

cat > /etc/systemd/system/upstream-gate.service <<EOF
# Generated by add_upstream_check_timer.sh. Edit the script, not this file.
[Unit]
Description=Publish to live what the users' votes allow
After=docker.service

[Service]
Type=oneshot
ExecStart=/bin/bash ${GATE} tick
EOF

cat > /etc/systemd/system/upstream-gate.timer <<'EOF'
# Generated by add_upstream_check_timer.sh. Edit the script, not this file.
[Unit]
Description=Daily upgrade gate

[Timer]
OnCalendar=*-*-* 05:00
Persistent=true

[Install]
WantedBy=timers.target
EOF

systemctl daemon-reload
systemctl enable --now upstream-check.timer >/dev/null 2>&1 \
    || { print_error "Could not enable upstream-check.timer."; print_action "systemctl status upstream-check.timer"; exit 1; }
print_status "Wrote upstream-check.service and .timer: Mondays 04:00, runs $CHECK"
systemctl enable --now upstream-gate.timer >/dev/null 2>&1 \
    || { print_error "Could not enable upstream-gate.timer."; print_action "systemctl status upstream-gate.timer"; exit 1; }
print_status "Wrote upstream-gate.service and .timer: daily 05:00, runs $GATE tick"

# Now as well, so a fresh drive does not wait for Monday: it builds every
# package and starts every environment its rows name.
systemctl start --no-block upstream-check.service
print_status "Started a first run in the background. On a Pi, building all packages takes about 45 minutes."
print_success "Next run: $(systemctl show upstream-check.timer -p NextElapseUSecRealtime --value)"
print_info "Log of a run: journalctl -u upstream-check.service"
