#!/usr/bin/env bash
set -e

# -d / --debug: trace every command. Stripped from "$@" so it never reaches the
# script's own argument parsing.
DEBUG_MODE=0
_dbg_args=()
for _a in "$@"; do
    case "$_a" in
        -d|--debug) DEBUG_MODE=1 ;;
        *)          _dbg_args+=("$_a") ;;
    esac
done
set -- ${_dbg_args+"${_dbg_args[@]}"}
unset _a _dbg_args
[ "$DEBUG_MODE" = "1" ] && set -x

# =============================================================================
# The daily refresh of end-of-support dates (collect_support_dates.sh), which
# the console's Runs on column and support card read. Writes support-dates.service
# and its timer, and runs it once now.
#
# It runs the root-owned copy under /usr/local/lib/linuxbasics, never the home
# clone: that copy is the one no other account can write to.
# =============================================================================

print_header()  { printf "\n\033[36m=== %s ===\033[0m\n" "$1"; }
print_info()    { printf "\033[36mℹ️ %s\033[0m\n" "$1"; }
print_status()  { printf "\033[34m🔧 %s\033[0m\n" "$1"; }
print_success() { printf "\033[32m✅ %s\033[0m\n" "$1"; }
print_warning() { printf "\033[33m⚠️  %s\033[0m\n" "$1"; }
print_action()  { printf "\033[33m👉 %s\033[0m\n" "$1"; }
print_error()   { printf "\033[31m❌ %s\033[0m\n" "$1"; }

[ "$EUID" -eq 0 ] || { print_error "This needs root: it writes systemd units."; print_action "sudo bash $0"; exit 2; }

PIPELINE_ROOT="/usr/local/lib/linuxbasics"
COLLECT="$PIPELINE_ROOT/hostings/scripts/collect_support_dates.sh"
[ -f "$COLLECT" ] || { print_error "No $COLLECT yet."; print_action "sudo bash $(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/add_pipeline_scripts.sh"; exit 1; }

print_header "Daily end-of-support dates"

NEED=()
command -v jq >/dev/null 2>&1 || NEED+=(jq)
[ -r /usr/share/distro-info/ubuntu.csv ] || NEED+=(distro-info-data)
if [ ${#NEED[@]} -gt 0 ]; then
    LOG="$(mktemp)"
    print_status "Installing ${NEED[*]}..."
    if ! DEBIAN_FRONTEND=noninteractive apt-get install -y "${NEED[@]}" >"$LOG" 2>&1; then
        print_error "Could not install ${NEED[*]}, output:"
        tail -20 "$LOG"
        print_info "Full log: $LOG"
        exit 1
    fi
    rm -f "$LOG"
fi

cat > /etc/systemd/system/support-dates.service <<EOF
# Generated by add_support_dates.sh. Edit the script, not this file.
[Unit]
Description=Refresh the end-of-support dates the hosting console shows
After=network-online.target
Wants=network-online.target

[Service]
Type=oneshot
ExecStart=/bin/bash ${COLLECT}
EOF

cat > /etc/systemd/system/support-dates.timer <<'EOF'
# Generated by add_support_dates.sh. Edit the script, not this file.
[Unit]
Description=Daily end-of-support dates

[Timer]
OnCalendar=*-*-* 05:30
RandomizedDelaySec=30min
Persistent=true

[Install]
WantedBy=timers.target
EOF

systemctl daemon-reload
systemctl enable --now support-dates.timer >/dev/null 2>&1 \
    || { print_error "Could not enable support-dates.timer."; print_action "systemctl status support-dates.timer"; exit 1; }
print_status "Wrote support-dates.service and .timer: daily around 05:30"

# Now as well, so the console has dates before tomorrow morning.
if systemctl start support-dates.service; then
    print_success "First run done: $(wc -l < /var/lib/linuxbasics/support.tsv) dates collected."
else
    print_warning "The first run could not reach every source; the timer tries again tomorrow."
    print_info "Why: journalctl -u support-dates.service -n 20"
fi
