#!/usr/bin/env bash
# A redraw needs a terminal. In a Jenkins log \r is not a carriage return, so
# every update lands as its own line and \033[K blanks it: seventeen units
# printed one line of text and sixteen empty ones. Silent there instead, since
# each of these loops already prints a summary when it finishes.
redraw() { [ -t 1 ] || return 0; printf "$@"; }
set -e

# -d / --debug: trace every command. Stripped from "$@" so it never reaches the
# script's own argument parsing.
DEBUG_MODE=0
_dbg_args=()
for _a in "$@"; do
    case "$_a" in
        -d|--debug) DEBUG_MODE=1 ;;
        *)          _dbg_args+=("$_a") ;;
    esac
done
set -- ${_dbg_args+"${_dbg_args[@]}"}
unset _a _dbg_args
[ "$DEBUG_MODE" = "1" ] && set -x

# =============================================================================
# Make this machine match /etc/hostings/hostings.conf.
#
#   ./maintain_services.sh            check, report, then apply
#   ./maintain_services.sh --check    check and report, change nothing
#   ./maintain_services.sh --prune    also delete what the config no longer lists
#   ./maintain_services.sh --verify   only check that every site answers
#
# This is layer 3 of the three-layer design: the generators are layer 1 and
# stay runnable on their own, and this calls them rather than replacing them.
# Nothing here duplicates what they do; it adds the three things they cannot do
# individually.
#
# 1. PRE-FLIGHT, ALWAYS
#
# The whole config is validated before the first write. A script that fails
# halfway leaves a machine in a state nobody designed, and that state is always
# harder to diagnose than a refusal.
#
# Errors block: a duplicate port or a missing credential file means the run
# cannot succeed. Warnings do not: DNS that does not resolve yet is worth
# knowing, but the rest of the run is still correct. If warnings blocked, a
# machine with one un-pointed record could never be configured at all.
#
# 2. DRIFT REPORT, BEFORE ACTING
#
#   ADD      the config says this should exist, the machine has no such thing
#   UPDATE   it exists, but differs from what the config would generate
#   OK       machine matches config
#   ORPHAN   on the machine, carries our generated header, no longer in config
#
# Printed before anything changes, so a re-run showing all OK is how you know it
# is genuinely a no-op rather than something you have to trust.
#
# 3. PRUNE, ONLY WHEN ASKED
#
# Orphans are reported by default and deleted only with --prune, and only ever
# files carrying "Generated by ... from hostings.conf". Anything a human wrote
# is invisible to this script by definition. That rule is what keeps a year of
# hand-written vhosts under backup_files/ safe from a --prune run.
# =============================================================================

export DEBIAN_FRONTEND=noninteractive

# --- Inline utility functions (always defined, no sourcing required) ---
print_status() {
    printf "\033[34m🔧 %s\033[0m\n" "$1"
}

print_success() {
    printf "\033[32m✅ %s\033[0m\n" "$1"
}

print_warning() {
    printf "\033[33m⚠️ %s\033[0m\n" "$1"
}

# Yellow means "this needs you", never "warning": a question, an instruction,
# a URL to go and open. Anything the reader cannot act on is cyan.
# Conventions: bash-installer-conventions.md.
print_action()  { printf "\033[33m👉 %s\033[0m\n" "$1"; }
print_info()    { printf "\033[36mℹ️ %s\033[0m\n" "$1"; }

print_error() {
    printf "\033[31m❌ %s\033[0m\n" "$1"
}

print_header() {
    printf "\n\033[36m=== %s ===\033[0m\n" "$1"
}

# Watch-only spinner: shows the command is alive but never signals it. Nothing
# here is safe to kill halfway, so there is no timeout and no SIGTERM.
#
# Silent when stdout is not a terminal. check_hostings.sh captures this script
# into the file the hosting manager displays, and carriage returns in a report
# are noise nobody can read.
show_spinner_watch_only() {
    local message="$1"
    shift
    if [ ! -t 1 ]; then "$@"; return $?; fi

    local frames=('⠋' '⠙' '⠹' '⠸' '⠼' '⠴' '⠦' '⠧' '⠇' '⠏')
    "$@" &
    local cmd_pid=$! tick=0
    while kill -0 "$cmd_pid" 2>/dev/null; do
        redraw '\r\033[K\033[34m%s %s\033[0m' "${frames[tick % 10]}" "$message"
        tick=$((tick + 1))
        sleep 0.2 || { printf "\n\033[31m❌ Progress loop aborted — sleep failed (filesystem trouble?)\033[0m\n"; break; }
    done
    local exit_code=0
    wait "$cmd_pid" || exit_code=$?
    redraw '\r\033[K'
    return $exit_code
}

# Wrapped commands whose output is needed write it to a file, so the spinner
# keeps the terminal to itself.
list_hosts_from() {
    LIST_HOSTS=1 SITES_CONF="$SITES_CONF" bash "$1" >"$2" 2>/dev/null || printf '' >"$2"
}

usage() {
    echo "Usage: $0 [--apply] [--check] [--prune] [--changed] [--only-row NAME]" >&2
    echo "" >&2
    echo "  --apply   make the machine match the config. The default, and the" >&2
    echo "            spelling a sudoers rule can match: a rule ending in '*'" >&2
    echo "            never matches a command run with no arguments at all." >&2
    echo "  --check   validate and report, change nothing" >&2
    echo "  --prune   delete generated files the config no longer lists" >&2
    echo "  --verify  only check that every published site answers, change nothing" >&2
    echo "  --changed write only the rows the last publish changed, worked out" >&2
    echo "            by changed_rows.sh from git. Falls back to writing" >&2
    echo "            everything whenever it cannot narrow it honestly." >&2
    echo "  --only-row NAME" >&2
    echo "            write only this row's unit, vhost and certificate." >&2
    echo "            Comma separated for several. The drift report still" >&2
    echo "            covers everything, so orphans stay visible." >&2
    echo "" >&2
    echo "Environment:" >&2
    echo "  SITES_CONF   override the config location" >&2
    echo "  CERT_EMAIL   passed through to add_site_certificates.sh" >&2
    echo "  ONLY_ROWS    same as --only-row" >&2
    exit 1
}

CHECK_ONLY=0
PRUNE=0
VERIFY_ONLY=0
CHANGED_ONLY=0
NO_ROWS_CHANGED=0
ONLY_ROWS="${ONLY_ROWS:-}"
while [ $# -gt 0 ]; do
    case "$1" in
        --apply)  shift ;;
        --check)  CHECK_ONLY=1; shift ;;
        --prune)  PRUNE=1; shift ;;
        --verify) VERIFY_ONLY=1; shift ;;
        --changed) CHANGED_ONLY=1; shift ;;
        --only-row)   ONLY_ROWS="$2"; shift 2 ;;
        --only-row=*) ONLY_ROWS="${1#--only-row=}"; shift ;;
        -h|--help) usage ;;
        *) print_error "Unknown option: $1"; usage ;;
    esac
done

# --only-row and --prune used to be refused together, because narrowing the
# WRITING once risked narrowing the drift report with it, and a narrowed report
# calls every untouched site an orphan.
#
# report_drift.sh removes that risk by construction: it reads the whole config
# and does not know ONLY_ROWS exists. The two can now run in one pass, which is
# what "apply my change, and clean up what my change orphaned" needs.


if [ "$EUID" -ne 0 ]; then
    print_error "This script requires sudo privileges to run properly."
    print_action "Please run with: sudo $0"
    exit 1
fi

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
. "$SCRIPT_DIR/config.sh" 2>/dev/null \
    || . /usr/local/lib/linuxbasics/hostings/scripts/config.sh 2>/dev/null \
    || conf_active() { printf '%s/hostings.conf' "$1"; }
SITES_CONF="${SITES_CONF:-$(conf_active "/etc/hostings")}"

if [ ! -f "$SITES_CONF" ]; then
    print_error "Config not found: $SITES_CONF"
    exit 1
fi
# --changed asks changed_rows.sh which rows the last publish moved. Every
# uncertainty there answers "all of them": exit 2 means it could not narrow it
# honestly, and a narrow answer that is wrong writes nothing where something
# was needed, which is the failure nobody notices until a site is down.
#
# THE BASE IS THE LAST COMMIT THIS MACHINE APPLIED, not HEAD~1. Measured
# 2026-09-12: a console save committed a row as Enabled = no, the tree then
# caught up over five commits, and changed_rows.sh's default HEAD~1 diffed the
# newest commit instead. It reported nothing changed, the write steps were
# skipped, and the run still printed "Machine matches" over a row whose unit was
# still active. A narrow answer that is wrong is exactly what the comment above
# warns about, and the default base was producing one.
#
# No record means no honest way to narrow, so every row is written.
APPLIED_MARK="/var/lib/hosting-manager/last-applied-commit"
if [ "$CHANGED_ONLY" -eq 1 ]; then
    _cr="$SCRIPT_DIR/changed_rows.sh"
    if [ ! -f "$_cr" ]; then
        print_info "changed_rows.sh is not next to this script, so every row is written."
    else
        _since=""
        if [ -r "$APPLIED_MARK" ]; then
            _since="$(tr -d ' \t\r\n' < "$APPLIED_MARK" 2>/dev/null || true)"
            if [ -n "$_since" ] \
               && ! git -C "$REPO_ROOT" rev-parse --verify --quiet "$_since^{commit}" >/dev/null 2>&1; then
                print_info "The last applied commit ${_since:0:7} is not in this tree, so every row is written."
                _since=""
            fi
        fi
        set +e
        if [ -n "$_since" ]; then
            print_info "Comparing against the last commit this machine applied, ${_since:0:7}."
            _rows="$(SITES_CONF="$SITES_CONF" SINCE="$_since" bash "$_cr")"
        else
            # Exit 2 downstream is "could not narrow honestly", which writes
            # every row. That is the right answer for a machine that has never
            # recorded an apply.
            _rows=""
            false
        fi
        _rc=$?
        set -e
        if [ "$_rc" -eq 0 ] && [ -n "$_rows" ]; then
            # A row the diff names but the config no longer holds was deleted.
            # That is a real change and its work is the prune, not a write, so
            # it is dropped from the scope rather than failing check_config's
            # typo guard, which cannot tell the two apart. The row test matches
            # changed_rows.sh: a setting line carries '=' before the first pipe
            # and a mailbox row is not a service row, so neither can claim a
            # deleted row's name.
            _kept=(); _gone=()
            while read -r _n; do
                [ -z "$_n" ] && continue
                set +e
                awk -F'|' -v n="$_n" '
                    /^[[:space:]]*#/ { next }
                    NF > 1 {
                        k = $1; gsub(/^[[:space:]]+|[[:space:]]+$/, "", k)
                        if (k ~ /=/ || k == "mailbox") next
                        gsub(/^[[:space:]]+|[[:space:]]+$/, "", $2)
                        if ($2 == n) found = 1
                    }
                    END { exit !found }' "$SITES_CONF"
                _look=$?
                set -e
                case "$_look" in
                    0) _kept+=("$_n") ;;
                    1) _gone+=("$_n") ;;
                    *) print_error "Could not read $SITES_CONF while checking row '$_n'. Nothing was changed."
                       exit 1 ;;
                esac
            done <<< "$_rows"
            if [ "${#_gone[@]}" -gt 0 ]; then
                print_info "No longer in the config, so not written: $(printf '%s,' "${_gone[@]}" | sed 's/,$//')"
            fi
            if [ "${#_kept[@]}" -gt 0 ]; then
                ONLY_ROWS="$(printf '%s,' "${_kept[@]}" | sed 's/,$//')"
                print_status "Changed rows: $ONLY_ROWS"
            elif [ "$PRUNE" -eq 1 ]; then
                NO_ROWS_CHANGED=1
                print_info "Every changed row was a removal, so nothing is written and the orphans are pruned."
            else
                NO_ROWS_CHANGED=1
                print_info "Every changed row was a removal, so nothing is written. Orphans are reported; add --prune to delete them."
            fi
        elif [ "$_rc" -eq 0 ]; then
            # An empty ONLY_ROWS means "every row" everywhere downstream, so
            # saying nothing here wrote all of them. Nothing changed means
            # nothing is written; orphans are still pruned, because they come
            # from the machine rather than from the diff.
            NO_ROWS_CHANGED=1
            print_status "No row changed since the previous commit, so nothing is written."
        else
            print_status "Could not narrow this to the rows that changed, so every row is written."
        fi
    fi
fi

export ONLY_ROWS

# -----------------------------------------------------------------------------
# Config readers. Duplicated verbatim rather than sourced, so this script stays
# runnable on its own on a machine that has only this file copied to it.
# -----------------------------------------------------------------------------
# Read once, in bash, rather than five forks per key.
#
# The cache below already meant one key was read once. The first read still
# cost sed, head, echo, sed and xargs: five processes, about 4ms each on this
# hardware, for one line of a file that was going to be read sixty times over.
# Measured 2026-08-24 with strace: 108 seds and 108 echos in a 4 second check.
#
# One pass loads every setting. A row line is not a setting: it holds pipes and
# no leading KEY=, and the pattern below cannot match it. First occurrence
# wins, which is what `head -n 1` did.
declare -A _CONF_CACHE=()
_CONF_LOADED=0
_conf_load() {
    local line key value
    [ "$_CONF_LOADED" = "1" ] && return 0
    _CONF_LOADED=1
    [ -f "$SITES_CONF" ] || return 0

    while IFS= read -r line || [ -n "$line" ]; do
        [[ "$line" =~ ^[[:space:]]*([A-Za-z_][A-Za-z0-9_]*)[[:space:]]*=(.*)$ ]] || continue
        key="${BASH_REMATCH[1]}"
        [ -n "${_CONF_CACHE[$key]+set}" ] && continue
        # A CRLF config leaves a carriage return on the end of the value, and
        # the two trims below only remove whitespace.
        value="${BASH_REMATCH[2]//$'\r'/}"
        value="${value%%#*}"
        value="${value#"${value%%[![:space:]]*}"}"
        value="${value%"${value##*[![:space:]]}"}"
        _CONF_CACHE[$key]="$value"
    done < "$SITES_CONF"
}

# Filled at the top level by the call below, never first from in here.
#
# conf_get is always called as $(conf_get ...), and a command substitution is a
# subshell. A cache filled inside one dies with it, which is why the
# memoisation this replaces never once served a second caller: every call took
# the slow path and nobody noticed, because the slow path was only five forks.
# Loading in the parent means each subshell inherits an array already full.
conf_get() {
    local key="$1" default="$2" value
    _conf_load
    value="${_CONF_CACHE[$key]:-}"
    echo "${value:-$default}"
}

_conf_load

conf_rows() {
    # One awk pass. A bash read loop over the whole file cost 0.2s per call.
    # A SETTING line is skipped even when it holds pipes, as PANEL lines do.
    awk '{ sub(/#.*/, "") } /^[[:space:]]*[A-Za-z_][A-Za-z0-9_]*[[:space:]]*=/ { next } /\|/' "$SITES_CONF"
}

# Does this row exist in this environment?
#
# The Envs field is empty for almost everything, meaning all of them. It exists
# because a test environment proves a build runs, which needs one instance of an
# application rather than one per customer: the four progress tenants are live
# only, and a single row covers test.
row_in_env() {
    local list="$1" env="$2" e
    list="$(echo "$list" | xargs)"
    [ -z "$list" ] || [ "$list" = "-" ] && return 0
    IFS=',' read -r -a _re <<< "$list"
    for e in "${_re[@]}"; do
        [ "$(echo "$e" | xargs)" = "$env" ] && return 0
    done
    return 1
}

# One place that decides what counts as yes. Accepts y, yes, true and 1 in any
# case; everything else, including empty and a dash, is no. Written once rather
# than as a case pattern at each site, because a value accepted in one script
# and rejected in another is the kind of inconsistency nobody finds quickly.
is_yes() {
    local v="$1"
    v="${v#"${v%%[![:space:]]*}"}"
    v="${v%"${v##*[![:space:]]}"}"
    case "${v,,}" in
        y|yes|true|1) return 0 ;;
        *)            return 1 ;;
    esac
}

# Is this row protected in this environment?
#
# Duplicated verbatim from add_app_vhosts.sh, which is the rule for this
# repo: every script stays runnable on a machine that has only that one file.
# The duplication is safe because this script cross-checks the generators
# against each other, so a copy that drifts is reported rather than discovered.
#
#   live:no, test:yes    per environment
#   yes / no             every environment
#
# An environment the row does not mention is protected, so a test copy cannot be
# published open by accident.
auth_in_env() {
    local spec="$1" env="$2" part k v
    spec="$(echo "$spec" | xargs)"

    case "$spec" in
        *:*) ;;
        *)   is_yes "$spec" && return 0 || return 1 ;;
    esac

    IFS=',' read -r -a _ae <<< "$spec"
    for part in ${_ae+"${_ae[@]}"}; do
        k="$(trim "${part%%:*}")"
        v="$(trim "${part#*:}")"
        if [ "$k" = "$env" ]; then
            is_yes "$v" && return 0 || return 1
        fi
    done

    # This script calls the first environment DEFAULT_ENV where the generator
    # calls it DEFAULT_PUBLISH. Same value, different name, so the copy is not
    # quite verbatim after all.
    [ "$env" = "$DEFAULT_ENV" ] && return 1
    return 0
}

# A field holding a single dash means empty. `| | |` cannot be counted by eye.
trim() {
    # Pure bash: no echo, no xargs. This is called once per field per row per
    # environment, and each fork costs more than the work it does.
    local v="$1"
    v="${v#"${v%%[![:space:]]*}"}"
    v="${v%"${v##*[![:space:]]}"}"
    [ "$v" = "-" ] && v=""
    printf '%s' "$v"
}

ERRORS=()
WARNINGS=()

err()  { ERRORS+=("$1"); }
warn() { WARNINGS+=("$1"); }

BASE_DOMAIN="$(conf_get BASE_DOMAIN "")"
[ -z "$BASE_DOMAIN" ] && err "No BASE_DOMAIN in $SITES_CONF"

IFS=',' read -r -a ALL_ENVS <<< "$(conf_get ENVS live)"
for i in "${!ALL_ENVS[@]}"; do ALL_ENVS[$i]="$(trim "${ALL_ENVS[$i]}")"; done
DEFAULT_ENV="${ALL_ENVS[0]}"

IFS=',' read -r -a PUBLISH_ENVS <<< "$(conf_get PUBLISH_ENVS "$(conf_get ENVS live)")"
for i in "${!PUBLISH_ENVS[@]}"; do PUBLISH_ENVS[$i]="$(trim "${PUBLISH_ENVS[$i]}")"; done

AUTH_USER_FILE="$(conf_get AUTH_USER_FILE /etc/apache2/.htpasswd-progress)"
AUTH_SESSION_KEY_FILE="$(conf_get AUTH_SESSION_KEY_FILE /etc/apache2/session-crypto.key)"

AVAILABLE_DIR="/etc/apache2/sites-available"
UNIT_DIR="/etc/systemd/system"
GENERATED_MARK="from /etc/hostings/hostings.conf"

# =============================================================================
# Verify every published site actually answers.
#
# The check lives in verify_sites.sh, one question per script, and that file
# carries the reasoning. This is the call, kept so --verify and the end of an
# apply behave as they always did.
# A missing file is reported, never silently skipped: a check that did not run
# must not read as a check that passed.
#
# Given `scoped`, it asks only the rows this run wrote. After an apply that is
# the honest question: the other sites were not touched. `--verify` on its own
# asks about all of them, which is why it is the caller that decides.
verify_sites() {
    local script="$SCRIPT_DIR/verify_sites.sh"
    if [ ! -f "$script" ]; then
        print_info "verify_sites.sh is not next to this script, so no site was verified."
        return 0
    fi
    local only=""
    [ "${1:-}" = "scoped" ] && only="$ONLY_ROWS"
    ONLY_ROWS="$only" SITES_CONF="$SITES_CONF" bash "$script"
}

# --verify answers one question: does every published site answer? It needs the
# config read and nothing else, so it skips validation, drift and the
# generators entirely.
if [ "$VERIFY_ONLY" -eq 1 ]; then
    # With --changed it asks only the rows the last publish moved, so the job's
    # own Verify stage does not re-ask all 26 hostnames after the apply already
    # asked the handful that changed.
    if [ "$CHANGED_ONLY" -eq 1 ]; then
        if [ "$NO_ROWS_CHANGED" -eq 1 ]; then
            print_status "No row changed, so there is nothing to ask about."
            exit 0
        fi
        verify_sites scoped
    else
        verify_sites
    fi
    exit $?
fi

print_header "Pre-flight"

# Two questions, two scripts, and they do not depend on each other: one reads
# the config, the other asks the generators. Started together and waited for,
# because the second is the slow one and nothing in the first is its input.
FLAGS_FILE="$(mktemp)"
CONFIG_LOG="$(mktemp)"
GEN_LOG="$(mktemp)"
REQ_FILE="$(mktemp)"
DRIFT_FILE="$(mktemp)"
trap 'rm -f "$FLAGS_FILE" "$CONFIG_LOG" "$GEN_LOG" "$DRIFT_FILE" "$REQ_FILE"' EXIT

need_script() {
    [ -f "$SCRIPT_DIR/$1" ] && return 0
    print_error "$1 is not next to this script, so the pre-flight cannot run."
    exit 1
}
need_script check_config.sh
need_script check_generators_agree.sh

set +e
FLAGS_OUT="$FLAGS_FILE" ONLY_ROWS="$ONLY_ROWS" SITES_CONF="$SITES_CONF" \
    bash "$SCRIPT_DIR/check_config.sh" >"$CONFIG_LOG" 2>&1 &
config_pid=$!
REQUESTED_OUT="$REQ_FILE" SITES_CONF="$SITES_CONF" \
    bash "$SCRIPT_DIR/check_generators_agree.sh" >"$GEN_LOG" 2>&1 &
gen_pid=$!
wait "$config_pid"; config_rc=$?
wait "$gen_pid";    gen_rc=$?
set -e

cat "$CONFIG_LOG"
cat "$GEN_LOG"

# What the config was found to need, read rather than worked out again.
NEEDS_CERT=0
HAVE_CERTBOT=0
ROW_COUNT=0
if [ -s "$FLAGS_FILE" ]; then
    # shellcheck disable=SC1090
    . "$FLAGS_FILE"
fi

if [ "$config_rc" -ne 0 ] || [ "$gen_rc" -ne 0 ]; then
    echo ""
    print_error "Pre-flight failed. Nothing was changed."
    exit 1
fi

print_success "Pre-flight passed: $ROW_COUNT rows, no errors."

# =============================================================================
# 3. Drift: what the config says, against what is on the machine
#
# Worked out by report_drift.sh, which reports and never writes. The list it
# leaves in DRIFT_FILE is what the pruner consumes, so the deciding happens
# once and the deleting happens somewhere else.
# =============================================================================

DRIFT_SCRIPT="$SCRIPT_DIR/report_drift.sh"
if [ ! -f "$DRIFT_SCRIPT" ]; then
    print_error "report_drift.sh is not next to this script, so drift cannot be reported."
    exit 1
fi
# The hostname list comes from the pre-flight rather than being asked for
# again: that question costs a whole pass over the config, and it has just
# been answered.
# ONLY_ROWS cleared, and stated rather than relied on: the drift report must see
# every row, because an orphan is by definition something no row asks for, and
# --prune acts on that list.
# The tree check below only reads git, so it runs while the drift is worked out
# and is printed after it, in the same place as before.
TREES_SCRIPT="$SCRIPT_DIR/check_tree_versions.sh"
TREES_LOG="$(mktemp)"
trap 'rm -f "$FLAGS_FILE" "$CONFIG_LOG" "$GEN_LOG" "$DRIFT_FILE" "$REQ_FILE" "$TREES_LOG"' EXIT
trees_pid=""
if [ -f "$TREES_SCRIPT" ]; then
    bash "$TREES_SCRIPT" >"$TREES_LOG" 2>&1 &
    trees_pid=$!
fi

DRIFT_OUT="$DRIFT_FILE" REQUESTED_HOSTS_FILE="$REQ_FILE" ONLY_ROWS= \
    SITES_CONF="$SITES_CONF" bash "$DRIFT_SCRIPT"

# Which commit is each copy of the repository on this machine running?
#
# A different question from drift, and it belongs beside it because it is the
# one that makes drift trustworthy: the answer above was produced by whatever
# code this tree happens to hold, and on 2026-08-27 two of the three trees were
# four commits behind with nothing anywhere saying so.
#
# Skipped in silence when the script is not beside this one, so a copy of
# maintain_services.sh on its own still runs and reports one question less. It
# must never fail the check: it reads and nothing more, and a check that goes
# red because a reporter tripped is a check that gets ignored.
if [ -n "$trees_pid" ]; then
    trees_rc=0
    wait "$trees_pid" || trees_rc=$?
    cat "$TREES_LOG"
    [ "$trees_rc" -eq 0 ] || print_info "The tree version check did not finish. Drift above is unaffected."
fi

ORPHAN_COUNT="$(grep -c '^ORPHAN ' "$DRIFT_FILE" || true)"

if [ "$CHECK_ONLY" -eq 1 ]; then
    echo ""
    print_success "--check: nothing was changed."
    if [ "$ORPHAN_COUNT" -gt 0 ]; then
        print_action "Run with --prune to delete the orphans above."
        if grep -q '^ORPHAN cert ' "$DRIFT_FILE"; then
            if [ "$HAVE_CERTBOT" -eq 1 ]; then
                print_info "A cert line means the certificate itself is deleted, not just a file."
            else
                print_info "A cert line is reported only: certbot is missing, so nothing would delete it."
            fi
        fi
    fi
    exit 0
fi


# =============================================================================
# 4. Apply, by calling layer 1. Nothing here duplicates what they do.
# =============================================================================
# What each generator did, so the end of the run says it in one place.
#
# This already named the failing script and stopped, which is the important
# half. What it did not say is what had ALREADY run by then, and an apply that
# stops in the middle leaves exactly that question: the operator sees one red
# line and a machine in an unknown state. Same shape as the create's report,
# and it is written where the console can read it. The owner, 2026-09-03.
APPLY_NAMES=()
APPLY_STATES=()
APPLY_NOTES=()

apply_report() {
    [ ${#APPLY_NAMES[@]} -eq 0 ] && return 0
    echo ""
    print_header "What the apply did"
    local i mark
    for i in "${!APPLY_NAMES[@]}"; do
        case "${APPLY_STATES[$i]}" in
            ok)     mark="\033[32m  ok     \033[0m" ;;
            failed) mark="\033[31m  FAILED \033[0m" ;;
            *)      mark="\033[34m  skipped\033[0m" ;;
        esac
        printf "%b%s\n" "$mark" " ${APPLY_NAMES[$i]}"
        [ -n "${APPLY_NOTES[$i]}" ] && printf "\033[36m           %s\033[0m\n" "${APPLY_NOTES[$i]}"
    done

    local f="/var/lib/hosting-manager/last-apply.json" tmp
    [ -d /var/lib/hosting-manager ] || return 0
    tmp="$(mktemp)"
    {
        printf '{"when":"%s","steps":[' "$(date -Is)"
        for i in "${!APPLY_NAMES[@]}"; do
            [ "$i" -gt 0 ] && printf ','
            printf '{"name":"%s","state":"%s","note":"%s"}' \
                "${APPLY_NAMES[$i]//\"/}" "${APPLY_STATES[$i]}" \
                "$(printf '%s' "${APPLY_NOTES[$i]}" | sed 's/\\/\\\\/g; s/"/\\"/g')"
        done
        printf ']}\n'
    } > "$tmp"
    install -m 0644 -o root -g root "$tmp" "$f" 2>/dev/null || true
    rm -f "$tmp"
}

apply_skipped() {
    APPLY_NAMES+=("$1"); APPLY_STATES+=("skipped"); APPLY_NOTES+=("${2:-}")
}

run_step() {
    local script="$1"; shift
    local path="$SCRIPT_DIR/$script"
    local label="$script${1:+ $*}"
    if [ ! -f "$path" ]; then
        APPLY_NAMES+=("$label"); APPLY_STATES+=("failed")
        APPLY_NOTES+=("not found next to this script")
        print_error "$script not found next to this script."
        apply_report
        exit 1
    fi
    print_header "$script"
    if ! bash "$path" "$@"; then
        APPLY_NAMES+=("$label"); APPLY_STATES+=("failed"); APPLY_NOTES+=("exited non-zero")
        print_error "$script failed. Stopping before anything else runs."
        # Printed BEFORE exiting, or the run that most needs the summary is the
        # one that never gets it.
        apply_report
        exit 1
    fi
    APPLY_NAMES+=("$label"); APPLY_STATES+=("ok"); APPLY_NOTES+=("")
}

# -----------------------------------------------------------------------------
# Self-healing: rows whose machine state is missing, whatever the diff said.
#
# --changed asks git which rows moved, and that answer can be right and still
# leave a row unbuilt. Measured 2026-09-04: three applications were created from
# the console and the applies reported "no row changed since the previous
# commit", because the console publishes the config and then pushes a second
# write-back commit, so each apply diffed the wrong pair. A row created from an
# EXISTING repository got no Jenkins jobs, no unit and no restart grant, and
# could never deploy.
#
# So the diff decides what to REWRITE, and this decides what is MISSING. A row
# with no unit joins the scope whatever git said: a missing unit is not an
# opinion.
# -----------------------------------------------------------------------------
HEAL_ROWS=()

# True when any existing unit of the row is enabled or running while the row
# says no, or disabled while it says yes. A missing environment unit is the ADD
# path's job.
unit_state_differs() {
    local name="$1" want="$2" e sfx unit state
    for e in $(conf_get ENVS live | tr ',' ' '); do
        sfx="$(conf_get "${e^^}_UNIT_SUFFIX" "")"
        unit="app-${name}${sfx}.service"
        [ -f "/etc/systemd/system/$unit" ] || continue
        state="$(systemctl is-enabled "$unit" 2>/dev/null || true)"
        if [ "$want" = "no" ]; then
            [ "$state" = "enabled" ] && return 0
            case "$(systemctl is-active "$unit" 2>/dev/null)" in
                active|activating|reloading) return 0 ;;
            esac
        else
            [ "$state" = "disabled" ] && return 0
        fi
    done
    return 1
}

NEED_JOBS=0
NEED_GRANT=0
JENKINS_JOBS_DIR="${JENKINS_JOBS_DIR:-/var/lib/jenkins/jobs}"
DEPLOY_SUDOERS="${DEPLOY_SUDOERS:-/etc/sudoers.d/010_jenkins-deploy}"

while IFS='|' read -r _t _n _p _pa _su _ds _op _au _repo _br _envs _aus _rm _rt _en _rest; do
    _t="$(printf '%s' "$_t" | tr -d ' \r')"
    _n="$(printf '%s' "$_n" | tr -d ' \r')"
    _repo="$(printf '%s' "$_repo" | tr -d ' \r')"
    _en="$(printf '%s' "$_en" | tr -d ' \r' | tr '[:upper:]' '[:lower:]')"
    [ -z "$_n" ] && continue
    case "$_t" in *=*) continue ;; esac

    if [ "$_t" = "app" ] && [ ! -f "/etc/systemd/system/app-${_n}.service" ]; then
        HEAL_ROWS+=("$_n")
        NEED_GRANT=1
        print_info "$_n has no unit on this machine, so it is written whatever the diff said."
    elif [ "$_t" = "app" ] && unit_state_differs "$_n" "$_en"; then
        # Measured 2026-09-15: a row disabled on 2026-09-12 kept its unit running
        # for three days, because no later diff named it.
        HEAL_ROWS+=("$_n")
        print_info "$_n has a unit whose enabled or running state does not match the config, so it is written whatever the diff said."
    elif [ "$_t" = "app" ] && [ -f "$DEPLOY_SUDOERS" ] && ! grep -q "app-${_n}\.service" "$DEPLOY_SUDOERS"; then
        NEED_GRANT=1
        print_info "$_n has a unit that jenkins may not restart, so the grants are rewritten."
    fi

    case "$_repo" in
        ''|'-'|'new') ;;
        # config.xml, not the directory. Jenkins holds every job in memory and
        # writes a skeleton back the moment one is removed from disk, so a bare
        # directory proves nothing: item 50 is the whole story. Measured here
        # on 2026-09-04, where a folder moved aside reappeared within seconds
        # carrying nothing but jobs/.
        *) if [ ! -f "$JENKINS_JOBS_DIR/$_n/config.xml" ]; then
               NEED_JOBS=1
               print_info "$_n names a repository and has no Jenkins folder, so the jobs are written."
           fi ;;
    esac
done < <(conf_rows)


# Folders whose row has gone. Same test add_jenkins_site_jobs.sh uses, so this
# cannot ask it to run over a folder it would refuse to touch: the generated
# mark, or no config.xml at all, which is the skeleton a running Jenkins writes
# back after a prune (item 50).
#
# Only with --prune, because reporting an orphan it is not allowed to delete
# would put a line in every apply that nobody can act on.
JENKINS_MARK="<!-- generated by add_jenkins_site_jobs.sh, safe to prune -->"
if [ "$PRUNE" -eq 1 ] && [ -d "$JENKINS_JOBS_DIR" ]; then
    for _dir in "$JENKINS_JOBS_DIR"/*/; do
        [ -d "$_dir" ] || continue
        _folder="$(basename "$_dir")"
        if [ ! -f "$_dir/config.xml" ]; then
            NEED_JOBS=1
            print_info "Jenkins folder '$_folder' has no config.xml, so the job generator is run to clear it."
            continue
        fi
        grep -qF "$JENKINS_MARK" "$_dir/config.xml" 2>/dev/null || continue
        _isrow=0
        while IFS='|' read -r _rt _rn _rrest; do
            _rn="$(printf '%s' "$_rn" | tr -d ' \r')"
            case "$_rt" in *=*) continue ;; esac
            [ "$_rn" = "$_folder" ] && { _isrow=1; break; }
        done < <(conf_rows)
        if [ "$_isrow" -eq 0 ]; then
            NEED_JOBS=1
            print_info "Jenkins folder '$_folder' has no row in the config, so it is pruned."
        fi
    done
fi

if [ "${#HEAL_ROWS[@]}" -gt 0 ]; then
    # Union, not replacement: the diff may name rows this scan does not.
    for _h in "${HEAL_ROWS[@]}"; do
        case ",${ONLY_ROWS}," in
            *,"$_h",*) ;;
            *) ONLY_ROWS="${ONLY_ROWS:+$ONLY_ROWS,}$_h" ;;
        esac
    done
    NO_ROWS_CHANGED=0
    export ONLY_ROWS
    print_status "Rows written to close a gap: $(printf '%s,' "${HEAL_ROWS[@]}" | sed 's/,$//')"
fi


if [ "$NO_ROWS_CHANGED" -eq 1 ]; then
    print_status "Skipping the write steps: no row changed."
    apply_skipped "the write steps" "no row changed"
else
run_step add_app_services.sh
# Every site vhost and the catch-all redirect name BASE_DOMAIN; without one
# (HomeRun, panels only) there is nothing for this step to write.
if [ -n "$BASE_DOMAIN" ]; then
    run_step add_app_vhosts.sh
else
    apply_skipped "add_app_vhosts.sh" "no BASE_DOMAIN, so no sites"
fi

if [ "$NEEDS_CERT" -eq 1 ] && command -v certbot >/dev/null 2>&1; then
    # The config is as good a source as the environment, and it is where the
    # address already lives. add_site_certificates.sh has always read both.
    CERT_EMAIL="${CERT_EMAIL:-$(conf_get CERT_EMAIL "")}"
    if [ -n "$CERT_EMAIL" ]; then
        export CERT_EMAIL
        run_step add_site_certificates.sh
        # Second pass: the first could only write :80 for any hostname whose
        # certificate did not exist yet.
        run_step add_app_vhosts.sh
    else
        apply_skipped "add_site_certificates.sh" "no CERT_EMAIL in the environment or the config"
        print_action "CERT_EMAIL is set neither in the environment nor in $SITES_CONF,"
        print_action "so certificates were skipped. Add to the config:"
        print_action "  CERT_EMAIL = you@example.com"
    fi
elif [ "$NEEDS_CERT" -eq 1 ]; then
    apply_skipped "add_site_certificates.sh" "certbot is not installed"
fi
fi

# Outside the guard for the same reason as the previews below, and only when the
# scan above found a gap: both are slow, one reloads Jenkins and the other
# validates sudoers, and neither belongs on every apply.
#
# --prune is forwarded, the same as add_panel_vhosts.sh below and for the same
# reason: this generator owns those folders, and without it a deleted row left
# its Jenkins jobs standing until somebody ran the script by hand.
#
# It is the generator that deletes them, never this script. Item 50 is the
# story of removing a Jenkins job with rm while Jenkins holds it in memory: it
# writes a skeleton straight back, and every folder left that way became
# permanently unprunable. add_jenkins_site_jobs.sh asks Jenkins first.
if [ "$NEED_JOBS" -eq 1 ]; then
    if [ "$PRUNE" -eq 1 ]; then
        run_step add_jenkins_site_jobs.sh --prune
    else
        run_step add_jenkins_site_jobs.sh
    fi
fi
if [ "$NEED_GRANT" -eq 1 ]; then
    run_step add_jenkins_deploy_permissions.sh
fi


# Outside the "no row changed" guard on purpose: PREVIEW_ROWS is not a row, so
# editing it alone leaves every row unchanged and the previews would never move.
# The script rewrites nothing it finds identical, and removes the previews the
# config no longer asks for.
run_step add_preview_vhosts.sh

# Same reason as previews: a PANEL line is a setting, not a row, so editing one
# leaves every row unchanged and the page would never be served. Pages whose own
# installer serves them are reported and left alone.
#
# --prune is forwarded, because this script owns the vhost and the firewall rule
# of every page it serves. Without it, deleting a page from the console took its
# line out of the config and left the port open with the page still answering,
# which is the opposite of what the button says.
if [ "$PRUNE" -eq 1 ]; then
    run_step add_panel_vhosts.sh --prune
else
    run_step add_panel_vhosts.sh
fi

# admin.<domain>, the console on every domain whose rows name somebody who can
# sign in. DERIVED, so nobody has to remember which domains have one: it is a
# consequence of the Owner field and the password file, and it changes on its
# own when either does.
#
# Outside the "no row changed" guard, and --prune forwarded, for the same reason
# as panels: an Owner taken off a row leaves a vhost with no reason to exist,
# and this script is the only thing that owns it.
# Only where the console is installed: admin.<domain> is the console.
if ! id -u hosting-manager >/dev/null 2>&1; then
    apply_skipped "add_admin_vhosts.sh" "no console on this machine"
elif [ -z "$BASE_DOMAIN" ]; then
    apply_skipped "add_admin_vhosts.sh" "no BASE_DOMAIN, so no admin.<domain>"
elif [ "$PRUNE" -eq 1 ]; then
    run_step add_admin_vhosts.sh --prune
else
    run_step add_admin_vhosts.sh
fi

# THE MAIL STACK, which this chain has never run. Until 2026-09-06 the mail
# scripts existed only in add_mail_stack.sh at install time, so a mailbox added
# from the console became a config row and nothing else: no Postfix domain, no
# delivery entry, no Dovecot account, and the job reported SUCCESS over it.
#
# add_postfix.sh, not add_dovecot.sh, and only that one: it chains add_dovecot.sh
# itself at its end, so calling both would run Dovecot twice.
#
# Outside the "no row changed" guard for the same reason previews and panels are:
# a mailbox row carries no vhost and no unit, so a change to one leaves every
# other check seeing nothing to do.
#
# Skipped when no mailbox row exists AND the mail configs no longer name a
# Let's Encrypt lineage. Running the mail stack on every apply of a machine that
# serves no mail is work nobody asked for.
#
# But "no mailbox rows" was the whole condition until 2026-09-07, and that is
# the one case where the scripts have work to do. Deleting the last mailbox row
# leaves Dovecot and Postfix still naming mail.<domain>, so the prune refuses to
# remove the lineage and the drift report calls it an orphan for ever. Both
# scripts stand down to the self-signed pair at zero rows, which b06fee1 built
# on 2026-09-06 for exactly this, and this guard is what stopped it running.
#
# Measured 2026-09-07: three mailbox rows deleted, then Fix drift pressed twice.
# Both times the full apply skipped add_postfix.sh and the same three orphans
# came back, with no button able to clear them.
mail_stand_down_owed() {
    grep -qs -- '/etc/letsencrypt/live/' \
        /etc/postfix/main.cf /etc/dovecot/conf.d/*.conf 2>/dev/null
}

if grep -qE '^[[:space:]]*mailbox[[:space:]]*\|' "$SITES_CONF" 2>/dev/null; then
    if [ -f "$SCRIPT_DIR/add_postfix.sh" ]; then
        run_step add_postfix.sh
    else
        apply_skipped "add_postfix.sh" "not found next to this script"
    fi
elif mail_stand_down_owed; then
    if [ -f "$SCRIPT_DIR/add_postfix.sh" ]; then
        print_info "No mailbox rows, but the mail configs still name a certificate."
        print_info "Running the mail stack so it stands down and releases the lineage."
        run_step add_postfix.sh
    else
        apply_skipped "add_postfix.sh" "not found next to this script"
    fi
else
    apply_skipped "add_postfix.sh" "no mailbox row, so there is no mail to serve"
fi

# =============================================================================
# 5. Prune, only when asked. prune_orphans.sh does it, from the list above.
# =============================================================================
if [ "$ORPHAN_COUNT" -gt 0 ]; then
    if [ "$PRUNE" -ne 1 ]; then
        echo ""
        print_info "$ORPHAN_COUNT orphaned file(s) left in place. Run with --prune to delete them."
        apply_skipped "prune orphans" "$ORPHAN_COUNT left in place, --prune not asked for"
    else
        PRUNER="$SCRIPT_DIR/prune_orphans.sh"
        if [ ! -f "$PRUNER" ]; then
            APPLY_NAMES+=("prune orphans"); APPLY_STATES+=("failed")
            APPLY_NOTES+=("prune_orphans.sh is not next to this script")
            print_error "prune_orphans.sh is not next to this script, so nothing was pruned."
            apply_report
            exit 1
        fi
        if bash "$PRUNER" --from "$DRIFT_FILE"; then
            APPLY_NAMES+=("prune orphans"); APPLY_STATES+=("ok")
            APPLY_NOTES+=("$ORPHAN_COUNT considered")
        else
            # Never fatal, and it never was: a prune that refuses something is
            # the guard working, not the apply failing.
            APPLY_NAMES+=("prune orphans"); APPLY_STATES+=("failed")
            APPLY_NOTES+=("see the prune output above")
        fi
    fi
else
    apply_skipped "prune orphans" "nothing orphaned"
fi



# Reported, never fatal. Two different questions live here: --apply answers
# "does the machine match the config", verify_sites answers "does every site
# answer correctly". A staging certificate makes the second one fail while the
# first is perfectly true, and letting that mark the apply failed hid the
# difference behind a red build.
#
# --verify still exits non-zero (:449). Asking that question on purpose and
# getting an answer is what it is for.
SITES_SHORT=0
if [ "$NO_ROWS_CHANGED" -eq 1 ]; then
    print_status "Nothing was written, so no site was asked. Use --verify for all of them."
    apply_skipped "ask the sites to answer" "nothing was written"
else
    if verify_sites scoped; then
        APPLY_NAMES+=("ask the sites to answer"); APPLY_STATES+=("ok"); APPLY_NOTES+=("")
    else
        SITES_SHORT=1
        # Not a failure of the apply, and the exit code below says so: the
        # config was applied, a site did not answer.
        apply_skipped "ask the sites to answer" "not every site answered, the config was still applied"
    fi
    [ "$SITES_SHORT" -eq 1 ] && print_info "Sites did not all answer. The config was still applied."
fi


# =============================================================================
# 5b. The vault follows the config: a mailbox sits in the entry of whoever owns
# its domain TODAY.
#
# A domain changing hands used to leave the mailbox and its password in the old
# owner's entry, where the new owner could not see it and the old one still
# could. Item 153.2, the owner 2026-09-20. Nothing is generated: sections are moved
# between existing entries, so a machine with no vault does nothing here.
#
# Never fatal. The machine is already correct; this is the copy in somebody
# else's password manager.
# =============================================================================
SYNC_OWNERS="$SCRIPT_DIR/person_entry.sh"
[ -f "$SYNC_OWNERS" ] || SYNC_OWNERS=/usr/local/sbin/person_entry.sh
if [ "$NO_ROWS_CHANGED" -eq 1 ]; then
    apply_skipped "1Password owners" "no row changed"
elif ! command -v op >/dev/null 2>&1; then
    apply_skipped "1Password owners" "no vault on this machine"
elif [ ! -f "$SYNC_OWNERS" ]; then
    apply_skipped "1Password owners" "person_entry.sh is not next to this script"
elif SITES_CONF="$SITES_CONF" bash "$SYNC_OWNERS" --sync-owners; then
    APPLY_NAMES+=("1Password owners"); APPLY_STATES+=("ok"); APPLY_NOTES+=("")
else
    apply_skipped "1Password owners" "the vault did not answer, the config was still applied"
fi
apply_report

# A CLAIM OF A MATCH IS A CLAIM ABOUT VERIFICATION, so it is not made when a
# step failed. On 2026-09-04 a prune deleted a certificate that 000-catchall
# still named, left Apache unable to parse its own config, and this line still
# printed "Machine matches" under a green build.
#
# The two are kept apart on purpose. A prune that REFUSES something is the guard
# working and stays non-fatal, as it always was. Apache being unable to parse
# its config is not a refusal, it is the machine broken, and that exits 4.
APPLY_FAILED=0
WROTE_VHOSTS=0
for _i in "${!APPLY_NAMES[@]}"; do
    [ "${APPLY_STATES[$_i]}" = "failed" ] && APPLY_FAILED=1
    case "${APPLY_NAMES[$_i]}:${APPLY_STATES[$_i]}" in
        *vhosts.sh*:ok) WROTE_VHOSTS=1 ;;
    esac
done
unset _i

echo ""
[ "$APPLY_FAILED" -eq 1 ] && \
    print_error "A step above FAILED, so whether the machine matches $SITES_CONF is unknown."

# Not scoped to this run: it answers "can Apache read its config right now",
# which outranks "my own steps went fine". The breakage may predate the run.
if command -v apachectl >/dev/null 2>&1 && ! apachectl configtest >/dev/null 2>&1; then
    print_error "Apache cannot parse its configuration. This machine is NOT serving what the config says."
    apachectl configtest 2>&1 | tail -5
    if [ "$WROTE_VHOSTS" -eq 1 ]; then
        print_action "A vhost step ran in this apply. Fix it with: sudo $SCRIPT_DIR/add_app_vhosts.sh"
    else
        print_action "No vhost step ran here, so this may predate this apply. Look at the file named above."
    fi
    exit 4
fi

# 3 is UNSTABLE in Jenkinsfile.machine--apply-config, which is what a failed
# step is: something was applied and something is not verified. Exiting 0 here
# is what let a FAILED prune finish green.
if [ "$APPLY_FAILED" -eq 1 ]; then
    exit 3
fi

print_success "Machine matches $SITES_CONF"

# RECORD WHAT WAS APPLIED, and only on the path where nothing failed. The next
# --changed run diffs from here rather than from HEAD~1, so a tree that catches
# up over several commits still writes the rows those commits moved.
#
# Written after the success line on purpose: a failed step exits 3 above and
# leaves the previous mark in place, so the next run re-considers the same span
# instead of believing work that did not happen.
if [ -d /var/lib/hosting-manager ]; then
    _head="$(git -C "$REPO_ROOT" rev-parse HEAD 2>/dev/null || true)"
    if [ -n "$_head" ]; then
        printf '%s\n' "$_head" > /var/lib/hosting-manager/last-applied-commit.tmp
        install -m 0644 -o root -g root \
            /var/lib/hosting-manager/last-applied-commit.tmp \
            /var/lib/hosting-manager/last-applied-commit 2>/dev/null || true
        rm -f /var/lib/hosting-manager/last-applied-commit.tmp
    fi
    unset _head
fi

# 3 means "applied, but a site did not answer", which is the whole reason the
# Jenkins job used to run a second, unscoped verify stage after this one. A
# distinct code says it here, so the job can mark itself UNSTABLE without asking
# 26 hostnames again. 0 and 1 keep their meanings for every other caller.
if [ "$SITES_SHORT" -eq 1 ]; then
    exit 3
fi
